### ISSUE TITLE
Panic from zmachine

### ISSUE THREAD

**Issue by aee11** [DeMille/encrusted#9]
Pressed back a few times and then issued a command and got the following error:
 
Unexpected zmachine error:

```
Error: Panicked at 'already borrowed: BorrowMutError', /checkout/src/libcore/result.rs:916:4
    at env.trace.t (https://sterlingdemille.com/encrusted/worker.js:1:18917)
    at t (https://sterlingdemille.com/encrusted/worker.js:1:8345)
    at wasm-function[160]:622
    at wasm-function[231]:310
    at wasm-function[230]:117
    at wasm-function[229]:123
    at wasm-function[382]:147
    at wasm-function[40]:139
    at wasm-function[122]:3616
    at b.feed (https://sterlingdemille.com/encrusted/worker.js:1:9896)
```

**Comment by DeMille** [comment]
Not a very helpful error stack huh? I must have stripped debug info when I deployed. I changed the build process to make stack traces better.

Was this after hitting back in your browser or the back/undo button?
